### ISSUE TITLE
 A small question regard the output from twisst2

### ISSUE THREAD

**Issue by ShaolinXU** [simonhmartin/twisst2#1]
Hi!

Thanks a lot for making such a great tool!

I have one small question regard the **topocounts.cs.gz** file: there is a column at the end of the file, which is named "**other**". May I ask what does the "other" topo corresponding to?

Thanks in advance

Best
Shaolin

**Comment by simonhmartin** [comment]
Shaolin,
Thank you for pointing that out. This is new to Twisst2. Subtrees with polytomies (also called multifurcations) go into the "other" column. The original R scripts for plotting that are provided at the original Twisst repository might have problems with the extra column. I will soon be uploading R scripts that can handle this.
Best wishes,
Simon
